language: node_js
node_js:
  - lts/*

cache:
  directories:
    - node_modules

install:
  - npm install hexo-cli -g
  - npm install

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "sugartxy"
  - git config user.email "tangxinye.tina@gmail.com"
  - git add .
  - git commit -m "Travis CI Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
  - git push --force --quiet "https://${GH_TOKEN}@github.com/sugartxy/sugartxy.github.io.git" master:master

branches:
  only:
    - master